name: Setup Go
description: |
  Setup Go

runs:
  using: "composite"
  steps:
    - id: go-version
      run: |
        echo "Go version is set to ${{ inputs.go-version }}"
        echo "GO_VERSION=${{ inputs.go-version }}" >> $GITHUB_ENV
      shell: bash
    - id: go-setup
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
