name: Lint

on:
  pull_request:
  push:
    branches:
      - 'master'
  release:
    types: [ published ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: ./.github/actions/setup-go
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --timeout=3m
