name: Test

on:
  pull_request:
  push:
    branches:
      - 'master'
  release:
    types: [ published ]

jobs:
  go-test:
    name: Run Go test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: ./.github/actions/setup-go
      - name: Run Go tests with coverage
        run: |
          go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
